backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "listings"
    label: "Listings"
    folder: "_data/listings"
    create: true
    slug: "{{slug}}"
    fields:
      - {name: "title", label: "Title", widget: "string"}
      - {name: "price", label: "Price", widget: "string"}
      - {name: "address", label: "Address", widget: "string"}
      - {name: "beds", label: "Bedrooms", widget: "number"}
      - {name: "baths", label: "Bathrooms", widget: "number"}
      - {name: "sqft", label: "Square Feet", widget: "number"}
      - {name: "description", label: "Description", widget: "text"}
      - {name: "images", label: "Images", widget: "list", field: {name: "image", label: "Image", widget: "image"}}
      - {name: "features", label: "Features", widget: "list", field: {name: "feature", label: "Feature", widget: "string"}}
      - {name: "status", label: "Status", widget: "select", options: ["For Sale", "Pending", "Sold"]}